print("Está é uma string")
print('Esta também é uma string')
print("Isto é 'uma' string correta, na qual tem aspas simples dentro")
print('Isto também é "uma" string correta, na qual tem aspas duplas dentro')
print('Isto é uma string \"com\" caractere de escape para não dar erro com as aspas simples')